# Generated by Django 4.2.8 on 2023-12-26 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chambeador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=50)),
                ('NombreEspecial', models.CharField(max_length=50)),
                ('Servicio', models.CharField(max_length=50)),
                ('Precio', models.CharField(max_length=50)),
                ('Contacto', models.CharField(max_length=50)),
            ],
        ),
    ]
